version: '3.9'
services:
  database:
    env_file:
      - .env
    container_name: visualsocial-container
    hostname: visualsocial-container
    image: postgres:13-alpine
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      TZ: America/Sao_Paulo